services:
    _defaults:
        public: false
        tags:
            - { name: monolog.logger, channel: cleverage_process_task }

    cleverage_flysystem_process.task.file_fetch:
        class: CleverAge\FlysystemProcessBundle\Task\FileFetchTask
        shared: false
        arguments: [!tagged_locator { tag: 'flysystem.storage', index_by: 'storage' }]
    CleverAge\FlysystemProcessBundle\Task\FileFetchTask:
        alias: cleverage_flysystem_process.task.file_fetch
        public: true

    cleverage_flysystem_process.task.list_content:
        class: CleverAge\FlysystemProcessBundle\Task\ListContentTask
        shared: false
        arguments: [!tagged_locator { tag: 'flysystem.storage', index_by: 'storage' }]
    CleverAge\FlysystemProcessBundle\Task\ListContentTask:
        alias: cleverage_flysystem_process.task.list_content
        public: true

    cleverage_flysystem_process.task.remove_file:
        class: CleverAge\FlysystemProcessBundle\Task\RemoveFileTask
        shared: false
        arguments:
            - '@logger'
            - !tagged_locator { tag: 'flysystem.storage', index_by: 'storage' }
    CleverAge\FlysystemProcessBundle\Task\RemoveFileTask:
        alias: cleverage_flysystem_process.task.remove_file
        public: true
